package com.cxwl.hurry.newdoorlock.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMG_FILE".
*/
public class ImgFileDao extends AbstractDao<ImgFile, Long> {

    public static final String TABLENAME = "IMG_FILE";

    /**
     * Properties of entity ImgFile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Img_localurl = new Property(1, String.class, "img_localurl", false, "img_localurl");
        public final static Property Img_uploadurl = new Property(2, String.class, "img_uploadurl", false, "img_uploadurl");
    }


    public ImgFileDao(DaoConfig config) {
        super(config);
    }
    
    public ImgFileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMG_FILE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"img_localurl\" TEXT," + // 1: img_localurl
                "\"img_uploadurl\" TEXT);"); // 2: img_uploadurl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMG_FILE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImgFile entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String img_localurl = entity.getImg_localurl();
        if (img_localurl != null) {
            stmt.bindString(2, img_localurl);
        }
 
        String img_uploadurl = entity.getImg_uploadurl();
        if (img_uploadurl != null) {
            stmt.bindString(3, img_uploadurl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImgFile entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String img_localurl = entity.getImg_localurl();
        if (img_localurl != null) {
            stmt.bindString(2, img_localurl);
        }
 
        String img_uploadurl = entity.getImg_uploadurl();
        if (img_uploadurl != null) {
            stmt.bindString(3, img_uploadurl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImgFile readEntity(Cursor cursor, int offset) {
        ImgFile entity = new ImgFile( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img_localurl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // img_uploadurl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImgFile entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImg_localurl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImg_uploadurl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImgFile entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImgFile entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImgFile entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
