package com.cxwl.hurry.newdoorlock.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KA".
*/
public class KaDao extends AbstractDao<Ka, Long> {

    public static final String TABLENAME = "KA";

    /**
     * Properties of entity Ka.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ka_id = new Property(1, String.class, "ka_id", false, "ka_id");
        public final static Property Yezhu_dianhua = new Property(2, String.class, "yezhu_dianhua", false, "yezhu_dianhua");
        public final static Property Guoqi_time = new Property(3, String.class, "guoqi_time", false, "guoqi_time");
    }


    public KaDao(DaoConfig config) {
        super(config);
    }
    
    public KaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ka_id\" TEXT," + // 1: ka_id
                "\"yezhu_dianhua\" TEXT," + // 2: yezhu_dianhua
                "\"guoqi_time\" TEXT);"); // 3: guoqi_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Ka entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ka_id = entity.getKa_id();
        if (ka_id != null) {
            stmt.bindString(2, ka_id);
        }
 
        String yezhu_dianhua = entity.getYezhu_dianhua();
        if (yezhu_dianhua != null) {
            stmt.bindString(3, yezhu_dianhua);
        }
 
        String guoqi_time = entity.getGuoqi_time();
        if (guoqi_time != null) {
            stmt.bindString(4, guoqi_time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Ka entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ka_id = entity.getKa_id();
        if (ka_id != null) {
            stmt.bindString(2, ka_id);
        }
 
        String yezhu_dianhua = entity.getYezhu_dianhua();
        if (yezhu_dianhua != null) {
            stmt.bindString(3, yezhu_dianhua);
        }
 
        String guoqi_time = entity.getGuoqi_time();
        if (guoqi_time != null) {
            stmt.bindString(4, guoqi_time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Ka readEntity(Cursor cursor, int offset) {
        Ka entity = new Ka( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ka_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // yezhu_dianhua
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // guoqi_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Ka entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKa_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYezhu_dianhua(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGuoqi_time(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Ka entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Ka entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Ka entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
